//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Number { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string Property1 { get; set; }
        public string Tour { get; set; }
    
        public virtual Referee Referee { get; set; }
        public virtual Deck Deck1 { get; set; }
        public virtual Deck Deck2 { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
